// LOGI / LOGIMOTORS — default content + UI strings (ka / en / ru)
// Admin-edited content is stored in localStorage and merged over these defaults.

export const STRINGS = {
  en: {
    navHome: 'Home', navAbout: 'About', navProducts: 'Products', navNews: 'News',
    navService: 'Service', navGallery: 'Gallery', navContacts: 'Contacts', navAdmin: 'Admin',
    heroCta1: 'Explore products', heroCta2: 'Get in touch',
    statYears: 'years of experience', statMachines: 'machines serviced',
    statParts: 'parts delivered', statSupport: 'support',
    secServices: 'What we do', secFeatured: 'Featured machines', secNews: 'Latest news',
    viewAll: 'View all', readMore: 'Read more', close: 'Close',
    filterAll: 'All', modeSale: 'Sale', modeRent: 'Rent', modeParts: 'Parts & wheels',
    fuelElectric: 'Electric', fuelDiesel: 'Diesel', fuelGasoline: 'Gasoline / LPG',
    condNew: 'New', condUsed: 'Used',
    capacity: 'Capacity', lift: 'Lift height', year: 'Year', brand: 'Brand',
    requestQuote: 'Request a quote', perMonth: '/mo',
    address: 'Address', phone: 'Phone', email: 'E-mail', web: 'Web',
    idCode: 'Company ID', legalName: 'Legal name', hours: 'Working hours',
    formName: 'Your name', formPhone: 'Phone', formMsg: 'Message', formSend: 'Send',
    formSent: 'Sent! We will contact you shortly.',
    serviceTitle: 'Service & repair', serviceCta: 'Book a service',
    ctaTitle: 'Need a machine or a part?', ctaSub: 'Call us — we answer fast.',
    anyBrand: 'Any brand · Any type · Gasoline / Diesel / Electric',
    aboutTitle: 'About the company', galleryTitle: 'Gallery', newsTitle: 'News',
    contactsTitle: 'Contacts', productsTitle: 'Products', noProducts: 'No products match the filter.',
    partsTab: 'Parts', wheelsTab: 'Wheels',
    wheelsDemoTitle: 'Forklift wheel — tire + rim assembly',
    wheelsDemoSub: 'Polyurethane and solid tires pressed onto steel rims — balanced, bolted and ready to mount on any forklift.',
    replay: 'Replay assembly',
    photo: 'photo'
  },
  ka: {
    navHome: 'მთავარი', navAbout: 'კომპანია', navProducts: 'პროდუქცია', navNews: 'სიახლეები',
    navService: 'სერვისი', navGallery: 'გალერეა', navContacts: 'კონტაქტი', navAdmin: 'ადმინი',
    heroCta1: 'პროდუქციის ნახვა', heroCta2: 'დაგვიკავშირდით',
    statYears: 'წლიანი გამოცდილება', statMachines: 'მომსახურებული ტექნიკა',
    statParts: 'მიწოდებული ნაწილი', statSupport: 'მხარდაჭერა',
    secServices: 'რას ვაკეთებთ', secFeatured: 'გამორჩეული ტექნიკა', secNews: 'ბოლო სიახლეები',
    viewAll: 'ყველას ნახვა', readMore: 'ვრცლად', close: 'დახურვა',
    filterAll: 'ყველა', modeSale: 'გაყიდვა', modeRent: 'გაქირავება', modeParts: 'ნაწილები და ბორბლები',
    fuelElectric: 'ელექტრო', fuelDiesel: 'დიზელი', fuelGasoline: 'ბენზინი / აირი',
    condNew: 'ახალი', condUsed: 'მეორადი',
    capacity: 'ტვირთამწეობა', lift: 'აწევის სიმაღლე', year: 'წელი', brand: 'ბრენდი',
    requestQuote: 'ფასის მოთხოვნა', perMonth: '/თვე',
    address: 'მისამართი', phone: 'ტელეფონი', email: 'ელ. ფოსტა', web: 'ვებ-გვერდი',
    idCode: 'საიდენტიფიკაციო კოდი', legalName: 'იურიდიული დასახელება', hours: 'სამუშაო საათები',
    formName: 'თქვენი სახელი', formPhone: 'ტელეფონი', formMsg: 'შეტყობინება', formSend: 'გაგზავნა',
    formSent: 'გაიგზავნა! მალე დაგიკავშირდებით.',
    serviceTitle: 'სერვისი და შეკეთება', serviceCta: 'სერვისზე ჩაწერა',
    ctaTitle: 'გჭირდებათ ტექნიკა ან ნაწილი?', ctaSub: 'დაგვირეკეთ — სწრაფად გიპასუხებთ.',
    anyBrand: 'ნებისმიერი ბრენდი · ნებისმიერი ტიპი · ბენზინი / დიზელი / ელექტრო',
    aboutTitle: 'კომპანიის შესახებ', galleryTitle: 'გალერეა', newsTitle: 'სიახლეები',
    contactsTitle: 'კონტაქტი', productsTitle: 'პროდუქცია', noProducts: 'ფილტრით პროდუქცია ვერ მოიძებნა.',
    partsTab: 'ნაწილები', wheelsTab: 'ბორბლები',
    wheelsDemoTitle: 'სატვირთველას ბორბალი — საბურავი + დისკი',
    wheelsDemoSub: 'პოლიურეთანის და მთლიანი საბურავები ფოლადის დისკებზე — დაბალანსებული, დამაგრებული და მზად ნებისმიერი სატვირთველისთვის.',
    replay: 'ანიმაციის გამეორება',
    photo: 'ფოტო'
  },
  ru: {
    navHome: 'Главная', navAbout: 'О компании', navProducts: 'Продукция', navNews: 'Новости',
    navService: 'Сервис', navGallery: 'Галерея', navContacts: 'Контакты', navAdmin: 'Админ',
    heroCta1: 'Смотреть продукцию', heroCta2: 'Связаться с нами',
    statYears: 'лет опыта', statMachines: 'единиц техники обслужено',
    statParts: 'запчастей поставлено', statSupport: 'поддержка',
    secServices: 'Что мы делаем', secFeatured: 'Избранная техника', secNews: 'Последние новости',
    viewAll: 'Смотреть все', readMore: 'Подробнее', close: 'Закрыть',
    filterAll: 'Все', modeSale: 'Продажа', modeRent: 'Аренда', modeParts: 'Запчасти и колёса',
    fuelElectric: 'Электро', fuelDiesel: 'Дизель', fuelGasoline: 'Бензин / Газ',
    condNew: 'Новый', condUsed: 'Б/у',
    capacity: 'Грузоподъёмность', lift: 'Высота подъёма', year: 'Год', brand: 'Бренд',
    requestQuote: 'Запросить цену', perMonth: '/мес',
    address: 'Адрес', phone: 'Телефон', email: 'E-mail', web: 'Сайт',
    idCode: 'Идентификационный код', legalName: 'Юридическое название', hours: 'Часы работы',
    formName: 'Ваше имя', formPhone: 'Телефон', formMsg: 'Сообщение', formSend: 'Отправить',
    formSent: 'Отправлено! Мы скоро свяжемся с вами.',
    serviceTitle: 'Сервис и ремонт', serviceCta: 'Записаться на сервис',
    ctaTitle: 'Нужна техника или запчасть?', ctaSub: 'Позвоните нам — мы отвечаем быстро.',
    anyBrand: 'Любой бренд · Любой тип · Бензин / Дизель / Электро',
    aboutTitle: 'О компании', galleryTitle: 'Галерея', newsTitle: 'Новости',
    contactsTitle: 'Контакты', productsTitle: 'Продукция', noProducts: 'Нет продукции по этому фильтру.',
    partsTab: 'Запчасти', wheelsTab: 'Колёса',
    wheelsDemoTitle: 'Колесо погрузчика — шина + диск',
    wheelsDemoSub: 'Полиуретановые и цельнолитые шины на стальных дисках — отбалансированы, закреплены и готовы к установке на любой погрузчик.',
    replay: 'Повторить анимацию',
    photo: 'фото'
  }
};

export const SERVICES = [
  { k: 'sale', num: '01',
    title: { en: 'Sale', ka: 'გაყიდვა', ru: 'Продажа' },
    desc: { en: 'New and used forklifts of any brand — gasoline, diesel and electric — selected for your tasks and budget.',
            ka: 'ახალი და მეორადი ავტოსატვირთველები ნებისმიერი ბრენდის — ბენზინი, დიზელი, ელექტრო — თქვენი ამოცანებისა და ბიუჯეტისთვის.',
            ru: 'Новые и б/у погрузчики любых брендов — бензин, дизель, электро — под ваши задачи и бюджет.' } },
  { k: 'rent', num: '02',
    title: { en: 'Rent', ka: 'გაქირავება', ru: 'Аренда' },
    desc: { en: 'Short- and long-term rental with maintenance included. A machine on your site within days.',
            ka: 'მოკლე და გრძელვადიანი გაქირავება მომსახურებით. ტექნიკა თქვენს ობიექტზე რამდენიმე დღეში.',
            ru: 'Краткосрочная и долгосрочная аренда с обслуживанием. Техника на вашем объекте за считанные дни.' } },
  { k: 'service', num: '03',
    title: { en: 'Service & repair', ka: 'სერვისი და შეკეთება', ru: 'Сервис и ремонт' },
    desc: { en: 'Diagnostics, scheduled maintenance and full regenerative repair for warehouse machinery of any manufacturer.',
            ka: 'დიაგნოსტიკა, გეგმიური მომსახურება და სრული აღდგენითი შეკეთება ნებისმიერი მწარმოებლის სასაწყობე ტექნიკისთვის.',
            ru: 'Диагностика, плановое обслуживание и полный восстановительный ремонт складской техники любого производителя.' } },
  { k: 'parts', num: '04',
    title: { en: 'Spare parts', ka: 'სათადარიგო ნაწილები', ru: 'Запчасти' },
    desc: { en: 'The full volume of spare parts for regenerative repair — original and analog — with minimal delivery timeframes.',
            ka: 'აღდგენითი შეკეთებისთვის საჭირო ნაწილების სრული ასორტიმენტი — ორიგინალი და ანალოგი — მიწოდების მინიმალური ვადებით.',
            ru: 'Весь объём запчастей для восстановительного ремонта — оригинал и аналог — с минимальными сроками поставки.' } },
  { k: 'wheels', num: '05',
    title: { en: 'Wheels & tyres', ka: 'ბორბლები და საბურავები', ru: 'Колёса и шины' },
    desc: { en: 'Polyurethane, solid and pneumatic wheels for every type of forklift and pallet truck.',
            ka: 'პოლიურეთანის, მთლიანი და პნევმატური ბორბლები ყველა ტიპის სატვირთველისა და პალეტის ურიკისთვის.',
            ru: 'Полиуретановые, цельнолитые и пневматические колёса для всех типов погрузчиков и тележек.' } }
];

export const DEFAULT_CONTENT = {
  texts: {
    heroTitle: { en: 'Machines that move your business',
                 ka: 'ტექნიკა, რომელიც თქვენს ბიზნესს ამოძრავებს',
                 ru: 'Техника, которая движет ваш бизнес' },
    heroSub: { en: 'Sale, rent, service and spare parts for every type of forklift — gasoline, diesel, electric. Any brand. 20+ years of experience.',
               ka: 'ნებისმიერი ტიპის ავტოსატვირთველას გაყიდვა, გაქირავება, სერვისი და სათადარიგო ნაწილები — ბენზინი, დიზელი, ელექტრო. ნებისმიერი ბრენდი. 20+ წლიანი გამოცდილება.',
               ru: 'Продажа, аренда, сервис и запчасти для любых погрузчиков — бензин, дизель, электро. Любой бренд. Более 20 лет опыта.' },
    about1: { en: 'The core of our business is the service of warehouse machinery, the sale of new and used warehouse equipment, and the full volume of spare parts required for regenerative repair. We work with warehouse machinery of any manufacturer — any brand.',
              ka: 'ჩვენი საქმიანობის ძირითადი მიმართულებაა სასაწყობე ტექნიკის სერვისი, ახალი და მეორადი ტექნიკის გაყიდვა და აღდგენითი შეკეთებისთვის საჭირო სათადარიგო ნაწილების სრული ასორტიმენტი. ვმუშაობთ ნებისმიერი მწარმოებლის ტექნიკაზე — ნებისმიერი ბრენდი.',
              ru: 'Основное направление деятельности — сервис складской техники, продажа новой и б/у складской техники, а также весь объём запчастей, необходимых для восстановительного ремонта. Мы работаем с техникой любых производителей — любой бренд.' },
    about2: { en: 'The concept of LOGIMOTORS LTD is to create the best conditions for the customer when purchasing the machinery or spare parts they need — with minimal delivery timeframes, guaranteed quality and a price that matches their choice.',
              ka: 'შპს „ლოგიმოტორსის“ კონცეფციაა შეუქმნას მომხმარებელს საუკეთესო პირობები საჭირო ტექნიკის ან ნაწილების შესაძენად — მიწოდების მინიმალური ვადებით, ხარისხის გარანტიით და მისთვის შესაფერისი ფასით.',
              ru: 'Концепция компании LOGIMOTORS LTD — создать для клиента лучшие условия при покупке необходимой техники или запчастей: минимальные сроки поставки, гарантия качества и цена, соответствующая его выбору.' },
    about3: { en: 'Our policy is focused on the customer and their priorities. Our employees are always ready for a meaningful dialogue to agree on mutually acceptable conditions for machinery service and parts delivery. We are always open to cooperation — get to know us, and you will appreciate the advantages of working with LOGIMOTORS LTD.',
              ka: 'კომპანიის პოლიტიკა ორიენტირებულია მომხმარებელზე და მის პრიორიტეტებზე. ჩვენი თანამშრომლები ყოველთვის მზად არიან შინაარსიანი დიალოგისთვის, რათა შეთანხმდნენ ურთიერთმისაღებ პირობებზე ტექნიკის მომსახურებასა და ნაწილების მიწოდებაზე. ჩვენ ყოველთვის ღია ვართ თანამშრომლობისთვის — გაგვიცანით და დარწმუნდებით „ლოგიმოტორსთან“ მუშაობის უპირატესობებში.',
              ru: 'Политика компании ориентирована на клиента и его приоритеты. Наши сотрудники всегда готовы к конструктивному диалогу для согласования взаимоприемлемых условий обслуживания техники и поставки запчастей. Мы всегда открыты к сотрудничеству — познакомившись с нами, вы оцените все преимущества работы с LOGIMOTORS LTD.' },
    serviceIntro: { en: 'Regenerative repair, scheduled maintenance and diagnostics for forklifts of any brand — gasoline, diesel and electric. Original and analog spare parts with minimal delivery timeframes.',
                    ka: 'აღდგენითი შეკეთება, გეგმიური მომსახურება და დიაგნოსტიკა ნებისმიერი ბრენდის სატვირთველისთვის — ბენზინი, დიზელი, ელექტრო. ორიგინალი და ანალოგი ნაწილები მიწოდების მინიმალური ვადებით.',
                    ru: 'Восстановительный ремонт, плановое обслуживание и диагностика погрузчиков любых брендов — бензин, дизель, электро. Оригинальные и аналоговые запчасти с минимальными сроками поставки.' }
  },
  products: [
    { id: 'p1', cat: 'forklift', mode: 'sale', fuel: 'electric', cond: 'used', brand: 'Toyota',
      name: { en: 'Toyota 8FBE20 electric forklift', ka: 'Toyota 8FBE20 ელექტრო სატვირთველა', ru: 'Электропогрузчик Toyota 8FBE20' },
      price: 14900, unit: '', capacity: '2.0 t', lift: '4.5 m', year: '2019', img: '' },
    { id: 'p2', cat: 'forklift', mode: 'sale', fuel: 'gasoline', cond: 'used', brand: 'Linde',
      name: { en: 'Linde H25T LPG forklift', ka: 'Linde H25T აირის სატვირთველა', ru: 'Газовый погрузчик Linde H25T' },
      price: 18500, unit: '', capacity: '2.5 t', lift: '3.7 m', year: '2018', img: '' },
    { id: 'p3', cat: 'forklift', mode: 'sale', fuel: 'diesel', cond: 'used', brand: 'Hyster',
      name: { en: 'Hyster H3.0FT diesel forklift', ka: 'Hyster H3.0FT დიზელის სატვირთველა', ru: 'Дизельный погрузчик Hyster H3.0FT' },
      price: 16800, unit: '', capacity: '3.0 t', lift: '4.0 m', year: '2017', img: '' },
    { id: 'p4', cat: 'forklift', mode: 'sale', fuel: 'electric', cond: 'new', brand: 'Jungheinrich',
      name: { en: 'Jungheinrich EFG 216 — new', ka: 'Jungheinrich EFG 216 — ახალი', ru: 'Jungheinrich EFG 216 — новый' },
      price: 32900, unit: '', capacity: '1.6 t', lift: '5.0 m', year: '2026', img: '' },
    { id: 'p5', cat: 'forklift', mode: 'rent', fuel: 'diesel', cond: 'used', brand: 'Komatsu',
      name: { en: 'Komatsu FD30T — rental', ka: 'Komatsu FD30T — გაქირავება', ru: 'Komatsu FD30T — аренда' },
      price: 780, unit: 'mo', capacity: '3.0 t', lift: '4.0 m', year: '2020', img: '' },
    { id: 'p6', cat: 'forklift', mode: 'rent', fuel: 'electric', cond: 'used', brand: 'Still',
      name: { en: 'Still RX20 — rental', ka: 'Still RX20 — გაქირავება', ru: 'Still RX20 — аренда' },
      price: 650, unit: 'mo', capacity: '2.0 t', lift: '4.2 m', year: '2021', img: '' },
    { id: 'p7', cat: 'wheels', mode: 'sale', fuel: null, cond: 'new', brand: 'Universal',
      name: { en: 'Polyurethane wheel set (4 pcs)', ka: 'პოლიურეთანის ბორბლების კომპლექტი (4 ც)', ru: 'Комплект полиуретановых колёс (4 шт)' },
      price: 240, unit: '', capacity: '', lift: '', year: '', img: '' },
    { id: 'p8', cat: 'parts', mode: 'sale', fuel: null, cond: 'new', brand: 'Universal',
      name: { en: 'Mast roller & chain kit', ka: 'ანძის გორგოლაჭებისა და ჯაჭვის კომპლექტი', ru: 'Комплект роликов мачты и цепи' },
      price: 390, unit: '', capacity: '', lift: '', year: '', img: '' }
  ],
  news: [
    { id: 'n1', date: '2026-06-12', img: '',
      title: { en: 'New arrivals: electric Jungheinrich EFG series in stock',
               ka: 'ახალი ჩამოსვლა: ელექტრო Jungheinrich EFG სერია მარაგშია',
               ru: 'Новое поступление: электрические Jungheinrich серии EFG на складе' },
      body: { en: 'A fresh batch of Jungheinrich EFG 216 electric forklifts has arrived at our Rustavi warehouse. Lithium-ready, 1.6 t capacity, available for immediate delivery.',
              ka: 'ჩვენს რუსთავის საწყობში ჩამოვიდა Jungheinrich EFG 216 ელექტრო სატვირთველების ახალი პარტია. 1.6 ტ ტვირთამწეობა, მზადაა დაუყოვნებელი მიწოდებისთვის.',
              ru: 'На наш склад в Рустави прибыла новая партия электропогрузчиков Jungheinrich EFG 216. Грузоподъёмность 1,6 т, доступны к немедленной поставке.' } },
    { id: 'n2', date: '2026-04-03', img: '',
      title: { en: 'Rental fleet expanded — 12 new machines',
               ka: 'გაქირავების პარკი გაფართოვდა — 12 ახალი ერთეული',
               ru: 'Арендный парк расширен — 12 новых машин' },
      body: { en: 'We added 12 machines to our rental fleet: diesel Komatsu and electric Still units from 1.5 to 3.5 tons. Short- and long-term contracts with service included.',
              ka: 'გაქირავების პარკს დაემატა 12 ერთეული: დიზელის Komatsu და ელექტრო Still 1.5-დან 3.5 ტონამდე. მოკლე და გრძელვადიანი კონტრაქტები მომსახურებით.',
              ru: 'Мы добавили в арендный парк 12 машин: дизельные Komatsu и электрические Still от 1,5 до 3,5 тонн. Краткосрочные и долгосрочные контракты с обслуживанием.' } },
    { id: 'n3', date: '2026-02-18', img: '',
      title: { en: '24/7 service support now available in Rustavi and Tbilisi',
               ka: '24/7 სერვის-მხარდაჭერა უკვე ხელმისაწვდომია რუსთავსა და თბილისში',
               ru: 'Сервисная поддержка 24/7 теперь доступна в Рустави и Тбилиси' },
      body: { en: 'Our mobile service teams now respond around the clock. One call — and a technician with parts is on the way to your warehouse.',
              ka: 'ჩვენი მობილური სერვის-ჯგუფები ახლა მთელი საათის განმავლობაში მუშაობენ. ერთი ზარი — და ტექნიკოსი ნაწილებით უკვე გზაშია თქვენი საწყობისკენ.',
              ru: 'Наши мобильные сервисные бригады теперь работают круглосуточно. Один звонок — и техник с запчастями уже едет на ваш склад.' } }
  ],
  gallery: [
    { id: 'g1', img: '', caption: { en: 'Warehouse fleet', ka: 'საწყობის ტექნიკა', ru: 'Складской парк' } },
    { id: 'g2', img: '', caption: { en: 'Service bay', ka: 'სასერვისო ცენტრი', ru: 'Сервисная зона' } },
    { id: 'g3', img: '', caption: { en: 'Parts warehouse', ka: 'ნაწილების საწყობი', ru: 'Склад запчастей' } },
    { id: 'g4', img: '', caption: { en: 'Delivery day', ka: 'მიწოდების დღე', ru: 'День поставки' } },
    { id: 'g5', img: '', caption: { en: 'Team at work', ka: 'გუნდი მუშაობისას', ru: 'Команда за работой' } },
    { id: 'g6', img: '', caption: { en: 'Rental yard', ka: 'გაქირავების ეზო', ru: 'Арендная площадка' } }
  ],
  contacts: {
    address: { en: '21 Gagarin St, Rustavi, Georgia', ka: 'რუსთავი, გაგარინის ქუჩა 21', ru: 'г. Рустави, ул. Гагарина 21' },
    legal: { en: 'LOGIMOTORS LTD', ka: 'შპს ლოგიმოტორსი', ru: 'ООО «ЛОГИМОТОРС»' },
    hours: { en: 'Mon–Fri 9:00–18:00 · Sat 10:00–15:00', ka: 'ორშ–პარ 9:00–18:00 · შაბ 10:00–15:00', ru: 'Пн–Пт 9:00–18:00 · Сб 10:00–15:00' },
    phone1: '(599) 585 148', phone2: '(555) 502 502',
    email: 'logi@logimotors.com', web: 'www.logimotors.com', idCode: '416289171'
  }
};

export const BRANDS = 'TOYOTA · LINDE · HYSTER · KOMATSU · JUNGHEINRICH · STILL · CAT · NISSAN · MITSUBISHI · CROWN · TCM · CLARK · HELI · DOOSAN · ANY BRAND · ';
